-- Import Posts from Old Database to WordPress
-- Run this SQL in phpMyAdmin after importing
-- Make sure to change table prefix if needed (default: wp_)

-- Insert posts into wp_posts table
INSERT INTO `wp_posts` (`post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_name`, `post_type`) VALUES
(1, '2024-12-05 00:00:00', '2024-12-05 00:00:00', '<p>Ngày 05/12/2024, Thạc sĩ - Luật sư Trần Hoàng Hải Phong thành viên TVL Legal System đã vinh dự đảm nhận vai trò ban giám khảo tại cuộc thi học thuật <i>"Tranh Tài Hùng Biện"</i> do Khoa Luật Thương mại, Trường Đại học Luật TP. Hồ Chí Minh tổ chức. Đây là một sự kiện nổi bật nhằm tạo sân chơi bổ ích cho sinh viên ngành luật, giúp các bạn rèn luyện kỹ năng tranh luận, tư duy phản biện và nâng cao kiến thức pháp luật.</p>', 'CUỘC THI HỌC THUẬT "TRANH TÀI HÙNG BIỆN" DO KHOA LUẬT THƯƠNG MẠI TRƯỜNG ĐẠI HỌC LUẬT TP. HỒ CHÍ MINH TỔ CHỨC', 'Thạc sĩ - Luật sư Trần Hoàng Hải Phong thành viên TVL Legal System đã vinh dự đảm nhận vai trò ban giám khảo tại cuộc thi học thuật "Tranh Tài Hùng Biện" do Khoa Luật Thương mại, Trường Đại học Luật TP. Hồ Chí Minh tổ chức.', 'publish', 'open', 'open', 'cuoc-thi-hoc-thuat-tranh-tai-hung-bien', 'post'),

(1, '2024-11-25 00:00:00', '2024-11-25 00:00:00', '<p>Ngày 25/11/2024, Luật sư Trần Vân Linh thành viên TVL Legal tham gia <strong>Hội nghị Truyền thông Luật Bình đẳng giới, Luật Trẻ em và Kỹ năng ứng xử trong môi trường học đường tại Trường tiểu học Yên Thế.</strong></p>', 'HỘI NGHỊ TRUYỀN THÔNG LUẬT BÌNH ĐẲNG GIỚI, LUẬT TRẺ EM VÀ KỸ NĂNG ỨNG XỬ TRONG MÔI TRƯỜNG HỌC ĐƯỜNG', 'Luật sư Trần Vân Linh thành viên TVL Legal tham gia Hội nghị Truyền thông Luật Bình đẳng giới, Luật Trẻ em và Kỹ năng ứng xử trong môi trường học đường tại Trường tiểu học Yên Thế.', 'publish', 'open', 'open', 'hoi-nghi-truyen-thong-luat-binh-dang-gioi', 'post'),

(1, '2024-11-21 00:00:00', '2024-11-21 00:00:00', '<p>Ngày 21/11/2024, Trường Đại học Hùng Vương, TP. Hồ Chí Minh đã tổ chức thành công talkshow đặc biệt với chủ đề <i><strong>"Sòng bạc" thương trường - Mua bán, sáp nhập và cạnh tranh dưới góc nhìn pháp lý"</strong></i></p>', 'CHƯƠNG TRÌNH TALKSHOW "SÒNG BẠC" THƯƠNG TRƯỜNG - MUA BÁN, SÁP NHẬP VÀ CẠNH TRANH DƯỚI GÓC NHÌN PHÁP LÝ', 'Trường Đại học Hùng Vương, TP. Hồ Chí Minh đã tổ chức thành công talkshow đặc biệt với chủ đề "Sòng bạc" thương trường - Mua bán, sáp nhập và cạnh tranh dưới góc nhìn pháp lý".', 'publish', 'open', 'open', 'chuong-trinh-talkshow-song-bac-thuong-truong', 'post'),

(1, '2024-12-22 00:00:00', '2024-12-22 00:00:00', '<p>Tối ngày 22/12/2024, TVL Legal System đã tổ chức Lễ kỷ niệm 16 năm hoạt động của Văn phòng Luật sư Trần Vân Linh, Year End Party để kết thúc năm 2024 và đồng thời Khai trương Công ty luật TNHH TVL tại Nhà Hàng Dìn Ký.</p>', 'KHAI TRƯƠNG CÔNG TY LUẬT TNHH TVL - KỶ NIỆM THÀNH LẬP 16 NĂM VĂN PHÒNG LUẬT SƯ TRẦN VÂN LINH', 'KHAI TRƯƠNG CÔNG TY LUẬT TNHH TVL- KỶ NIỆM THÀNH LẬP 16 NĂM VĂN PHÒNG LUẬT SƯ TRẦN VÂN LINH - YEAR AND PARTY 2024', 'publish', 'open', 'open', 'khai-truong-cong-ty-luat-tnhh-tvl', 'post'),

(1, '2025-03-17 00:00:00', '2025-03-17 00:00:00', '<p>Thiết thực tổ chức các hoạt động chào mừng kỷ niệm 50 năm Ngày giải phóng miền nam, thống nhất đất nước (30/4/1975 - 30/4/2025) và tổ chức các hoạt động Tháng Thanh niên năm 2025.</p>', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG TUYÊN TRUYỀN LUẬT THANH NIÊN 2020 TẠI TRƯỜNG TH - THCS - THPT THANH BÌNH', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG - GIÁM ĐỐC CÔNG TY LUẬT TNHH TVL TUYÊN TRUYỀN LUẬT THANH NIÊN 2020 TẠI TRƯỜNG TH - THCS - THPT THANH BÌNH.', 'publish', 'open', 'open', 'luat-su-tran-hoang-hai-phong-tuyen-truyen-luat-thanh-nien-2020', 'post'),

(1, '2025-03-24 00:00:00', '2025-03-24 00:00:00', '<p>Hiện nay, bạo lực học đường, bạo hành và xâm hại trẻ em đang trở thành vấn đề nhức nhối, diễn ra ngày càng phức tạp và khó kiểm soát.</p>', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG TUYÊN TRUYỀN LUẬT TRẺ EM TẠI TRƯỜNG TIỂU HỌC CÁCH MẠNG THÁNG TÁM', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG – GIÁM ĐỐC CÔNG TY LUẬT TNHH TVL TUYÊN TRUYỀN LUẬT TRẺ EM, KỸ NĂNG PHÒNG CHỐNG XÂM HẠI VÀ BẠO LỰC HỌC ĐƯỜNG.', 'publish', 'open', 'open', 'luat-su-tran-hoang-hai-phong-tuyen-truyen-luat-tre-em-cach-mang-thang-tam', 'post'),

(1, '2025-03-15 00:00:00', '2025-03-15 00:00:00', '<p>Sáng ngày 15/3/2025, Đảng ủy, Ủy ban nhân dân, Ủy ban MTTQ Việt Nam Phường cùng các tổ chức chính trị - xã hội Phường 12 tổ chức Hội nghị tuyên truyền.</p>', 'HỘI NGHỊ TUYÊN TRUYỀN NGÀY PHÁP LUẬT - LUẬT SƯ TRẦN VÂN LINH PHỔ BIẾN LUẬT PHÒNG, CHỐNG BẠO LỰC GIA ĐÌNH', 'HỘI NGHỊ TUYÊN TRUYỀN NGÀY PHÁP LUẬT - LUẬT SƯ TRẦN VÂN LINH TUYÊN TRUYỀN, PHỔ BIẾN LUẬT PHÒNG, CHỐNG BẠO LỰC GIA ĐÌNH; LUẬT HÔN NHÂN VÀ GIA ĐÌNH.', 'publish', 'open', 'open', 'hoi-nghi-tuyen-truyen-ngay-phap-luat-phong-chong-bao-luc-gia-dinh', 'post'),

(1, '2025-03-23 00:00:00', '2025-03-23 00:00:00', '<p>Hưởng ứng Tháng Thanh niên 2025 và hoạt động "Ngày Chủ nhật Xanh" lần thứ 156.</p>', 'LUẬT SƯ TRẦN VÂN LINH TUYÊN TRUYỀN LUẬT BẢO VỆ MÔI TRƯỜNG VÀ NGHỊ ĐỊNH 53/2024/NĐ-CP', 'LUẬT SƯ TRẦN VÂN LINH - TRƯỞNG VĂN PHÒNG LUẬT SƯ TRẦN VÂN LINH TUYÊN TRUYỀN LUẬT BẢO VỆ MÔI TRƯỜNG VÀ NGHỊ ĐỊNH 53/2024/NĐ-CP HƯỚNG DẪN LUẬT TÀI NGUYÊN NƯỚC 2023.', 'publish', 'open', 'open', 'luat-su-tran-van-linh-tuyen-truyen-luat-bao-ve-moi-truong', 'post'),

(1, '2025-03-30 00:00:00', '2025-03-30 00:00:00', '<p>Viện Khoa học pháp lý Trọng tài (ARI) - Chiêu sinh khóa bồi dưỡng kiến thức pháp luật về Trọng tài thương mại Tháng 4/2025.</p>', 'VIỆN KHOA HỌC PHÁP LÝ TRỌNG TÀI (ARI) - CHIÊU SINH KHÓA BỒI DƯỠNG PHÁP LUẬT TRỌNG TÀI THÁNG 4/2025', 'VIỆN KHOA HỌC PHÁP LÝ TRỌNG TÀI (ARI) - THÔNG BÁO CHIÊU SINH KHÓA BỒI DƯỠNG PHÁP LUẬT TRỌNG TÀI CƠ BẢN THÁNG 4/2025', 'publish', 'open', 'open', 'vien-khoa-hoc-phap-ly-trong-tai-ari-chieu-sinh', 'post'),

(1, '2025-03-31 00:00:00', '2025-03-31 00:00:00', '<p>Sáng ngày 31/03/2025, Ủy ban nhân dân Phường 12 tổ chức xây dựng kế hoạch tuyên truyền Luật Trẻ em.</p>', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG TUYÊN TRUYỀN LUẬT TRẺ EM TẠI TRƯỜNG THCS NGÔ QUYỀN', 'NGÀY 31/3/2025 - LUẬT SƯ TRẦN HOÀNG HẢI PHONG - GIÁM ĐỐC CÔNG TY LUẬT TNHH TVL TUYÊN TRUYỀN LUẬT TRẺ EM TẠI TRƯỜNG THCS NGÔ QUYỀN, PHƯỜNG 12, QUẬN TÂN BÌNH.', 'publish', 'open', 'open', 'luat-su-tran-hoang-hai-phong-tuyen-truyen-luat-tre-em-ngo-quyen', 'post'),

(1, '2025-04-05 00:00:00', '2025-04-05 00:00:00', '<p>LUẬT SƯ TRẦN HOÀNG HẢI PHONG - GIÁM ĐỐC CÔNG TY LUẬT TNHH TVL - DIỄN GIẢ BUỔI TẬP HUẤN KỸ NĂNG.</p>', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG - DIỄN GIẢ BUỔI TẬP HUẤN KỸ NĂNG "VIẾT BẢN LUẬN CỨ VÀ TRANH BIỆN"', 'LUẬT SƯ TRẦN HOÀNG HẢI PHONG - GIÁM ĐỐC CÔNG TY LUẬT TNHH TVL - DIỄN GIẢ BUỔI TẬP HUẤN KỸ NĂNG "VIẾT BẢN LUẬN CỨ VÀ TRANH BIỆN" - HÀNH TRANG CHO CHIẾN BINH CÔNG LÝ.', 'publish', 'open', 'open', 'luat-su-tran-hoang-hai-phong-dien-gia-buoi-tap-huan-ky-nang', 'post');

-- Note: After running this SQL, you need to:
-- 1. Go to WordPress Admin > Settings > Permalinks and click "Save Changes" to flush rewrite rules
-- 2. Upload featured images manually or use a plugin to import from URLs
